// <auto-generated />
namespace MVC_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _202002180957085_InitialCreate_IdChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202002180957085_InitialCreate_IdChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202002181047500_202002180957085_InitialCreate_IdChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
